server.port=8410
spring.application.name=device-service
spring.datasource.jdbcUrl=jdbc:postgresql://127.0.0.1:5442/iotdb
spring.datasource.current-schema=iot
spring.datasource.username=iot_user
spring.datasource.password=123456a@
spring.datasource.entity-path=com.huysama.builderDto.enitties.iot
spring.datasource.driver-class-name=org.postgresql.Driver
spring.custom-datasource.maximum-pool-size=10
spring.custom-datasource.minimum-idle=5



