services:
  traefik:
    image: traefik:v3.4
    command:
      - --configFile=/etc/traefik/traefik.yml
    environment:
      - OTEL_PROPAGATORS=b3
    ports:
      - "80:80"
      - "8088:8080"
      - "8082:8082"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./my-volumes/traefik/certs:/certs
      - ././microservice-huysama-traefik/traefik.yml:/etc/traefik/traefik.yml
      - ././dynamic:/etc/traefik/dynamic
      - ./my-volumes/oauth2proxy/ca/minica.pem:/usr/local/share/ca-certificates/minica.crt
#    depends_on:
#      - jaeger
    networks:
      - huysama-network

  consul-discovery:
    image: consul:1.15
    ports:
      - "8500:8500"
    networks:
      - huysama-network
    restart: unless-stopped

  keycloak:
    image: keycloak/keycloak:26.0.7
    command:
      - start-dev
      - --hostname-strict=false
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres/keycloak
      - --db-username=admin
      - --db-password=admin
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=https"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    ports:
      - "9090:8080"
    networks:
      - huysama-network
    depends_on:
      - traefik
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:15.13
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./my-volumes/data/postgres:/var/lib/postgresql/data
    #      - ./my-volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - huysama-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
    networks:
      - huysama-network
    restart: unless-stopped
  website:
    build:
      context: ./microservice-huysama-admin-panel
      dockerfile: Dockerfile
    networks:
      - huysama-network
    ports:
      - "7001:7001"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.website.rule=Host(`website.localtest.me`)"
#      - "traefik.http.routers.website.entrypoints=https"
#      - "traefik.http.routers.website.tls=true"
#      - "traefik.http.services.website.loadbalancer.server.port=7001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.tls=true"
      - "traefik.http.routers.website.rule=Host(`website.localtest.me`)"
      - "traefik.http.routers.website.entrypoints=admin"              # ✅ thay vì https
      - "traefik.http.services.website.loadbalancer.server.port=7001"

  authentication-service:
    build:
      context: ./microservice-huysama-authentication-service
      dockerfile: Dockerfile
#    image: authentication-service:latest
    platform: linux/amd64
    environment:
      - CONSUL_HOST=consul-discovery
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "4301:4301"
    depends_on:
      - consul-discovery
      - traefik
    networks:
      - huysama-network
#    restart: unless-stopped
#  jaeger:
#    image: jaegertracing/all-in-one:1.56
#    ports:
#      - "16686:16686"    # Jaeger UI
#      - "6831:6831/udp"  # Jaeger agent (UDP, thường cho client libs cũ hơn)
#      - "5778:5778"      # Sampling config
#      # OpenTelemetry Collector mặc định dùng các cổng sau:
#      - "4317:4317"      # OTLP gRPC receiver
#      - "4318:4318"      # OTLP HTTP receiver
#    networks:
#      - huysama-network
networks:
  huysama-network:
    driver: bridge
